### ISSUE TITLE
Using Grinder with step assist seems to break progress.

### ISSUE THREAD

**Issue by robertm1771** [TeamBR-Modding/NeoTech#101]
I have the sojourner's Sash from Botania that provides jump boost and step assist this breaks the grinder from neotech removing sash restores the grinders function.

**Comment by Dyonovan** [comment]
I am guessing the sojourners sash does something to fall damage. If this is the case, having the grinder not work with it is actually a good thing.

I will take a look into it though.

**Comment by pauljoda** [comment]
This is not an issue. The point of the grinder is to be an early game ore processing. Allowing the player to bypass the damage takes the point out and invalidates the crusher. For that reason, this is not an issue. Thanks for the information

**Comment by robertm1771** [comment]
There is no damage from jumping up and down. Can you explain how it invalidates the crusher?

Also things not working as intended seem not to be an issue. It always has been in my 30 years of programing experience.

Should not close issues just to keep them from showing assign them to there proper place.

**Comment by Dyonovan** [comment]
The higher you jump down unto the plate, the more work it does. If you are high enough when you fall onto the plate, you will die as normal, but you get a LOT of work done.

It seems that the sojourner's sash from Botania cancels out fall damage. As the amount of work done is totally based on fall distance/damage, there is not much we can do when another mod cancels that out.

**Comment by pauljoda** [comment]
The crusher is invalidated because if you can just fall from 100s of blocks for free and take no damage you can grind things very easily for free. That is not at all how we intended for it to work. This was close because we do not see this as a problem. Our machine is doing what we told it to and this is one of the things we told it to do. It isn't just a brushing off a real issue just because we don't want to see it. I honestly do not find this to be an issue. The machine was balanced around the player with normal capabilities not fall resistance added by other mods. 

Since you have 30 years of experience, feel free to clone the repo and make the changes for your own personal use. I just ask you don't release it as it is not your mod. 

Thank you for your input and please respect ours

**Comment by robertm1771** [comment]
I respect any option that can be explained closing it and just saying it was invalid made no sense from your short comment.

Telling me there is no way to make the machine work as you intend it to work with items that limit fall damage would have resolved the issue in my mind.

Now that its been explained maybe I can help. Why not make the machine do a base amount of work if fall distance check is 0.0 as its coded now you have to have a positive fall distance for it to work at all. Revisiting and doing this might resolve more issues being reported down the road.

**Comment by Dyonovan** [comment]
No worries. Sometimes its really hard to communicate through text.

That is a very good idea tho. One of the issues with doing it as you suggest, which we had to look into to see if it was possible, is that the method is called and return 0.0 even if your standing on the pressure plate.

I don't think there is a perfect solution to this, but remembering this is only meant to be a very early game machine, we don't think its worth the effort or time to look deeper in it.

Though after saying that, if you have any suggestions, please keep them coming.
