### ISSUE TITLE
Add Support for Mo'Shiz ore

### ISSUE THREAD

**Issue by Dyonovan** [TeamBR-Modding/NeoTech#12]
http://minecraft.curseforge.com/mc-mods/62536-mo-shiz-mod

**Comment by DatrixTHLK** [comment]
I guess this mod has stopped being updated then because I've been waiting for that update for about a month or two now and I usually don't wait half that long. I'm a patient person but I may just abandon this mod seeing as how this mod hasn't been updated in a while. As this is the only tech mod that adds in an electric furnace, furnace gen, and a crusher along with item pipes.

**Comment by Dyonovan** [comment]
Rewrite has a dynamic crusher recipe system that matches OreDict ore->dust->ingot on first run. This will create a json which can be edited to add more things. Initial release later today
