### ISSUE TITLE
Duplication Glitch with dimentional crates, tested in 1.8.9-2.3.5

### ISSUE THREAD

**Issue by Matts** [TeamBR-Modding/NeoTech#157]
The dimensional crates are really glitchy as far as i have tested them in the FTB Unstable pack.
When placing them, it creates a lot of server side lag.
I don't exactly recall how but i have been able to duplicate items within the crates and the crates  themselfs without too much hassle

**Comment by Dyonovan** [comment]
What version of NeoTech are you using?

**Comment by Matts** [comment]
The one used in FTB Unstable 3.0.29, according to the modinfo it is 2.3.5

**Comment by Dyonovan** [comment]
There have been a few reports of dupes with the crates, but I was never able to reproduce. Thanks to some users, it was found to be an issue of another mod (Dont know which one in particular, just from a list) This mod has since been updated.

Try updating to the latest unstable and see if that fixes it.
