### ISSUE TITLE
could you please check why your RF pipe does not connects to the advanced generators mod output... 

### ISSUE THREAD

**Issue by winsrp** [TeamBR-Modding/NeoTech#207]
What Version of NeoTech are you using: using version 2.4.1
If possible, did you break and replace the block: yes several times.

using advanced generators 0.9.16.6

plz, it has a very cool multiblock generator that is the only thing missing to connect with your pipes.

you guys are the best..

**Comment by pauljoda** [comment]
The issue is they are not using the RF API correctly. When the API moved to 1.8.9, receivers and providers were separated from the IEnergyHandler and made sub classes. He only extends IEnergyHandler and not the sub classes we are looking for (the correct way to use the API). Without the information provided by the child classes, we are not able to interface with this mod
