### ISSUE TITLE
Electric logger seems a bit to eager

### ISSUE THREAD

**Issue by dominx** [TeamBR-Modding/NeoTech#245]
What Version of NeoTech are you using:
2.4.1 I'm playing FTB Unstable

If possible, did you break and replace the block:
Yes, it helped but it's not the point.

I've placed unupgraded Electric Logger. I was living in the jungle biome with bushes covering most of the ground. Logger cleared all wood and leaves in about 20 block radius before I've broken and replaced it. Meanwhile in its planting area I got pretty much solid wall of oak. Shots: http://imgur.com/a/P4BRW All that area was pretty much covered by jungle vegetation. 

It seems that Logger chops any wood connected by leaves in a big radius. I know that it's not obvious where a tree ends but this seems a bit excessive.

**Comment by pauljoda** [comment]
Yes that is what it does. In order to make sure it doesn't miss trees, it follows connections as it builds the map of things to chop. It is a bit eager, but its the best way around the randomness of trees. It isn't really meant to be used in a forest, but as its own farm. All tree farms have the same issue all the way back into 1.7.10
