### ISSUE TITLE
Electric Armor comments

### ISSUE THREAD

**Issue by Majestyc2k1** [TeamBR-Modding/NeoTech#288]
What Version of NeoTech are you using: 1.9-3.0.5

I am a bit underwhelmed by the Electric Armor.
1. As steel, it should provide a bit more protection than iron.
2. Need a Step-Assist upgrade (especially if using the Jetpack upgrade).
3. Make the keys for Hover and Glide configurable. It was awkward trying to hold the Ctrl and W keys at the same time. Maybe make Hover toggle on and off? What is the LMENU key?
4. Add Plating Upgrade to increase the defense point value of the armor. 
5. Add Durability Upgrade to increase durability.

**Comment by pauljoda** [comment]
The armor is in severe infancy. It will be getting more attention soon

**Comment by pauljoda** [comment]
To give more info:
1. Yes it will provide more protection, I just used iron as a base
2. Sadly I will have to make this. I don't like doing it as it isn't super clean but I can do so.
3. That is for sure the final plan. LMENU is left alt. 
4. Not particularly possible. Armor defense points are tied to the material, not the item itself. Which is why protection is implemented to allow upgrading
5. Durability is based on the battery stored. They use energy and therefore don't have a "durability". Use a battery as a component when upgrading and it will up the max storage

**Comment by pauljoda** [comment]
Closing, but I will keep this as a reference when continuing.
