### ISSUE TITLE
Thermal Binder upgrade issue

### ISSUE THREAD

**Issue by Rene211** [TeamBR-Modding/NeoTech#340]
I have no crash but i cant upgrade for example more than one upgrade on a motherboard. No combination or upgrading the same one again works.

How can i fix that ?

Rene :)

**Comment by xenanthropy** [comment]
I'm having the same problem. I just assumed that maybe for some reason you can only install one processor on, but then I noticed it has a counter for the amount of processors you have on, so that debunked that. I have the right amount of tin in (I actually have a full bucket) and placing a blank motherboard in the left slot, and 2 or more processor upgrades in any of the 4 slots, it will not work. It shows the right tick amount when you hover your mouse over the arrow in the middle (200 tick added per processor) but clicking start does nothing, but it does work with just one processor.

**Comment by xenanthropy** [comment]
D'oh! I'm dumb. There is no problem here, you just have to stack the processors on top of each other to get it to work! You can't have the processors/hard drives in different slots, having them in one stack worked fine. @Rene211, you should close this now.
