### ISSUE TITLE
[Suggestion & Issue]

### ISSUE THREAD

**Issue by Jynx2700** [TeamBR-Modding/NeoTech#413]
What Version of NeoTech are you using: 1.10.2

With the lack of wires and pipes in the build I am running I have resorted to using the battery blocks as wires essentially. Problem is mostly that there is very little actual information in the block or on the wiki. Also sometimes the blocks do not seem to pass power through each other and just sit there full. 

Perhaps some sort of side configuring could force a power flow, or maybe I was overdoing the max amount of RF the blocks can accept. Not sure, but more than likely.

Also, tooltips need love, or an in-game book. There is no real information on what each piece of your mod does other than having to watch your description videos on YouTube.

Anyways, have a good one

-Jynx

**Comment by pauljoda** [comment]
Thanks for the info. To clear up some of your concerns I do plan on adding a little more info in the tool tips of the items. At the moment, the bulk of the info for the mod is located in the info tabs for each machine. I prefer this to an in game book as it is more involved. I do plan on getting the wiki filled at some point soon though. The main reason there isn't much info is this is a full rewrite. Down to the nuts and bolts all has been changed so at the moment we are in the testing phase. As soon as I feel it is stable, there will be a large push in polish and documentation. Some of the recent changes for the next release reflect this. 

As for pipes/wires. This is something I have though about alot. We used to have a full pipe system for fluids/items/power. However, it was a pain to maintain and stopped progress. In order to move forward I removed them. On top of that, 1.10.2 holds a huge variety of power movement so I didn't feel it needed. We may add a basic power system in the future, but will likely not be a traditional pipe/wire. I don't want to give any info as I haven't decided on it yet. 

And the last point, the batteries are made to be a simple block. They store RF, and output to touching blocks. Nothing fancy and perhaps one day in the future they will be, but for now they are not high on my list. I want to do new things like new machines and such, but making yet another battery block while potentially fun can keep me from doing that. Neotech hasn't had new content in a long time and I want to focus on that. 

I hope that answers your concerns, be sure to keep me updated with more as you play with the mod!
