### ISSUE TITLE
[1.11.2-5.0.0] crash while sneaking at Fluid Generator 

### ISSUE THREAD

**Issue by kreezxil** [TeamBR-Modding/NeoTech#421]
What Version of NeoTech are you using: 1.11.2-5.0.0

1. make sure holoinventory mod is installed in the client
1. place Fluid Generator
1. hold sneak and look at generator

Please Pastebin.com the crash Report and put link here:
https://pastebin.com/VJnnwH7E

HoloInventory appears to be the culprit of the crash so I posted there first: https://github.com/dries007/HoloInventory/issues/33

**Comment by dries007** [comment]
It's because [this](https://github.com/TeamBR-Modding/NeoTech/blob/master/src/main/java/com/teambrmodding/neotech/common/tiles/AbstractMachine.java#L456-L474) function is not capable of handling the `null` as a direction. (`null` is used as the 'internal' direction by many things, including HoloInventory.)

**Comment by pauljoda** [comment]
Since the time of creating this, Forge enabled null to be used. At first, they said never null, now seems it is accepted. A fix may be made if I continue work, I still haven't decided yet

**Comment by kreezxil** [comment]
I would love more options for 1.12.2 so please continue work.

**Comment by pauljoda** [comment]
No longer working on pre 1.14 versions, these issues will be considered during the rewrite
