### ISSUE TITLE
The game lags like mad.

### ISSUE THREAD

**Issue by coolgaza16** [TeamBR-Modding/NeoTech#43]
If u have a chest extracting out to another chest and the chest is full items bounce around continuously and this causes me huge FPS issues took me a while to figure it out but breaking the pipes and replacing them with a hopper fixed my issue. Not sure how u can fix this, except maybe a buffer or have it check for an available slot. P.s. Using version 2.05 on ftb unstable.

**Comment by pauljoda** [comment]
Thanks for the issue. This is something I was interested in testing. The pipes are smart but dumb at the same time. The only thing that actually does work is the extraction pipe. All other pipes are passive so the extraction starts sending because it finds an inventory that it can use. I'm not sure how I'm going to go about making them smarter but I am working on it. I have a few ideas though so there will be some changes soon.

**Comment by coolgaza16** [comment]
Ok I updated to 2.08 btw and this is still the case. Thanks for getting back to me. XD

**Comment by Dyonovan** [comment]
Should be fixed in the new 1.8.9 release. Going to close this but if you still find it happening just reopen it.

**Comment by coolgaza16** [comment]
You have a 1.8.9 release. That's great can't wait to play with it
