### ISSUE TITLE
fluids and items not working 

### ISSUE THREAD

**Issue by tiarnia** [TeamBR-Modding/NeoTech#64]
liquid tank  is ticking constantly and if you have 2 of the fluid interface pipes set to both they continuously move liquid back and forth for no reason 

if you have a tank with water in it and its set to output then when the tank is full the extra liquid is destroyed or lost till the output is empty

also items jump out of the pipes and if you can get it to not do that they have the same issue with bouncing things constantly drives server tick loop crazzy also half the time the pipes dont save your I/O selection

**Comment by pauljoda** [comment]
I've done a little testing and fixing. The issue with the bouncing seems to be with the routing algorithm. I had forgot to do a simple check before adding itself as a valid source. This will fix the tanks from draining and destroying, the bouncing, and the items moving around. Also, there was a call to reset IO on GUI open I forgot to remove so it will remember your selections. Item bounce back and pop out is the only way to handle item movement without a valid source. It now won't send unless it has somewhere to go so that issue should be solved.

On the subject of tanks, if you are on the version using the 3d modeled tank and not the full cube that should not be an issue. I've tested this personally and it does not tick unless a change in state occurs. If you are experiencing this please provide me with some more information on the tank. As for two pipes sending to each other, if you have not configured the IO correctly then the will send to each other because they view each other as a valid source. Set one to input only on that face and this should solve your problem.

Let me know if you run into any more issues

**Comment by tiarnia** [comment]
nice thanks
