### ISSUE TITLE
Fluid Interface crash

### ISSUE THREAD

**Issue by AngelCry** [TeamBR-Modding/NeoTech#83]
at first i want to sa sorry in advance, if issue caused not by your mod, but as i dont see any other in crahlog, i guess it is. short explanation: build simple fluid tank, build altar (from BloodMagic) and fill it with life essense, then connect them by pipes and fluid interfaces. pipes start transfer fluid but soon MC crashes. error is ArrayIndexOutOfBoundsException:
https://gist.github.com/AngelCry/d86ae01933df961f48d9
MC 1.8.9, Forge 1724, BloodMagic-1.8.9-2.0.0-15, Bookshelf-1.8.9-2.2.8, NeoTech-1.8.9-2.3.3, simplefluidtanks-1.8.9-1.3.0.2.thanks :)

**Comment by pauljoda** [comment]
Hmm. This seems to be a mod not implementing fluid tanks normally. I'll double check before I play the blame game

**Comment by AngelCry** [comment]
then BuildCraft pipes a bit more... careful, because they do not crash. i guess BloodMagic altar can be somewhat special tank. at least as i know, is wont allow you just take as many as you want, is have some "bandwidth" (which can be increased by upgrades). btw is just my assumption, i have no idea if is related or no.

**Comment by pauljoda** [comment]
The issue is with blood magic. In order to get information about their tank, there is a method I call. All mods are expected to implement this method. They did not. We have talked with the team over there and they are fixing it. Thanks for the report we will do what we can to catch crashes as well should a mod be implemented wrong
